inherit_from: .rubocop_todo.yml

AllCops:
  RunRailsCops: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/spring'
    - 'db/**/*'
    - 'doc/bin/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Style/GuardClause:
  MinBodyLength: 3

Style/Semicolon:
  AllowAsExpressionSeparator: true
